name: 🐛 Bug Report
description: Template for reporting bugs or defects in InfiniLore
title: 'BugReport | '
assignees: []
labels:
  - bug
  - priority
projects:
  - InfiniLore/1
type: Bug

# ------------------------------------------
#             ACTUAL FORM BODY
# ------------------------------------------
body:
  - type: markdown
    attributes:
      value: >+
        ## 🦆 InfiniLore : Bug Report

        **Please use this template to report bugs and defects in the InfiniLore platform.**  

  - type: markdown
    attributes:
      value: ---

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Bug Description
      description: Please describe the bug in detail. What are the steps to reproduce it?
      placeholder: ex. The application crashes when trying to create a new lorescope.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 🧐 Expected Behavior
      description: What was the expected behavior? How should it function?
      placeholder: ex. The application should not crash when creating a lorescope.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: What steps did you take to encounter the issue?
      placeholder: ex. 1. Open the app 2. Click "Create Lorescope" 3. Observe the crash.

  - type: textarea
    id: browser-system
    attributes:
      label: 🖥 Browser/OS Information
      description: Include browser or OS version where the bug was encountered.
      placeholder: ex. Google Chrome v95, Windows 10

  - type: dropdown
    id: progran-section
    attributes:
      label: 📐 Application Section
      description: What does feature belong to
      options:
        - 🔗 API
        - 🎨 UI
        - 🚨 Testing
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |-
        ---
        ### 💡 Notes & Logs 🌟
        - Any logs, stack traces, or screenshots would be extremely helpful in diagnosing the issue.
        
        ---
        
        _Template generated with [Issue Forms Creator](https://issue-forms-creator.netlify.app)_
